apiVersion: v1
kind: Pod
metadata:
  name: echod
spec:
  containers:
    - name: echod
      image: "gcr.io/hightowerlabs/echod@sha256:aba48d60ba4410ec921f9d2e8169236c57660d121f9430dc9758d754eec8f887"
